18_getting_started_with_django/exercises/pizzeria_app/pizzas/urls.py
"""Defines URL patterns for the pizzas app."""

from django.urls import path
from . import views

app_name = 'pizzas'

urlpatterns = [
    # Home page
    path("", views.index, name="index"),

    # Show all pizzas
    path("pizzas/", views.pizzas, name="pizzas"),

    # Detail page for a single pizza
    path("pizzas/<int:pizza_id>/", views.pizza, name="pizza"),
]

18_getting_started_with_django/exercises/pizzeria_app/pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('pizzas.urls', namespace='pizzas')),
]

18_getting_started_with_django/exercises/pizzeria_app/pizzas/models.py
from django.db import models

# Create your models here.
class Pizza(models.Model):
    """The choice of pizza."""
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = 'toppings'

    def __str__(self):
        return self.name
    

18_getting_started_with_django/exercises/pizzeria_app/pizzas/views.py
from django.shortcuts import render
from .models import Pizza

# Create your views here.

def index(request):
    """The home page for the pizzeria app."""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    """Show all pizzas."""
    pizzas = Pizza.objects.order_by('name')
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    """Show a single pizza and its toppings."""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('name')  # type: ignore
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)

18_getting_started_with_django/exercises/pizzeria_app/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria home</a> - 
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}{% endblock content %}

18_getting_started_with_django/exercises/pizzeria_app/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
  <p>The Pizzeria app offers a variety of delicious pizzas to choose from.</p>
{% endblock content %}

18_getting_started_with_django/exercises/pizzeria_app/pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}
  <p>{{ pizza }} pizza</p>

  <p>Toppings:</p>
  <ul>
    {% for topping in toppings %}
      <li>{{ topping }}</li>
    {% empty %}
      <li>There are no toppings for this pizza yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}

18_getting_started_with_django/exercises/pizzeria_app/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}
  <p>Available pizzas</p>
  
  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
      </li>
    {% empty %}
      <li>No pizzas are available at the moment.</li>
    {% endfor %}
  </ul>
{% endblock content %}