20_styling_and_deploying_an_app/blog_app/Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include('users.urls', namespace='users')),
    path("", include('blogs.urls', namespace='blogs'))
]

20_styling_and_deploying_an_app/blog_app/blogs/urls.py
"""Defines URL patterns for blogs."""

from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    # Home page
    path("", views.index, name='index'),

    # Page for adding new blogposts
    path("new_blogpost/", views.new_blogpost, name='new_blogpost'),

    # Page for editing a blogpost
    path("edit_blogpost/<int:blogpost_id>/", views.edit_blogpost, name='edit_blogpost')
]

20_styling_and_deploying_an_app/blog_app/users/urls.py
"""Defines URL patterns for users"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "users"

urlpatterns = [
    # Login page
    path("login/", auth_views.LoginView.as_view(template_name="users/login.html"),
         name="login"),
    # Logout page
    path("logout/", views.logout_view, name="logout"),
    # Registration page
    path("register/", views.register, name='register'),
]

20_styling_and_deploying_an_app/blog_app/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    """Create a blogpost"""
    title = models.CharField(max_length=30)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.title

20_styling_and_deploying_an_app/blog_app/users/models.py
from django.db import models

# Create your models here.

20_styling_and_deploying_an_app/blog_app/blogs/forms.py
from django import forms

from .models import BlogPost

class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': 'Title:', 'text': 'Text:'}
        widgets = {
            'title': forms.TextInput(attrs={'size': 30}),
            'text': forms.Textarea(attrs={'cols': 80})
        }

20_styling_and_deploying_an_app/blog_app/blogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import BlogPost
from .forms import BlogPostForm

# Create your views here.
def index(request):
    """The home page for blogs"""
    blogposts = BlogPost.objects.order_by('-date_added')
    context = {'blogposts': blogposts}
    return render(request, 'blogs/index.html', context)

@login_required
def new_blogpost(request):
    """Add a new blogpost."""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = BlogPostForm()
    else:
        # POST data submitted; process data.
        form = BlogPostForm(request.POST)
        if form.is_valid():
            new_blogpost = form.save(commit=False)
            new_blogpost.owner = request.user
            new_blogpost.save()
            return HttpResponseRedirect(reverse('blogs:index'))
    
    context = {'form': form}
    return render(request, 'blogs/new_blogpost.html', context)

@login_required
def edit_blogpost(request, blogpost_id):
    """Edit an existing blogpost."""
    blogpost = BlogPost.objects.get(id=blogpost_id)
    if blogpost.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current blogpost.
        form = BlogPostForm(instance=blogpost)
    else:
        # POST data submitted; process data.
        form = BlogPostForm(instance=blogpost, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:index'))
        
    context = {'blogpost': blogpost, 'form': form}
    return render(request, 'blogs/edit_blogpost.html', context)

20_styling_and_deploying_an_app/blog_app/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))
        
    context = {'form': form}
    return render(request, 'users/register.html', context)

20_styling_and_deploying_an_app/blog_app/blogs/templates/blogs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Learning Log</title>
    {% bootstrap_css %}
    <style>
      body { background-color: #222; color: #ccc; }
      .page-header { border-bottom: 1px solid #444; color: #ccc; }
      .jumbotron {
          background-color: #333;
          color: #ffffff;
          border: 1px solid #444;
      }
      ul {
          list-style-type: none;
          padding-left: 0;
      }
      hr {
          border-top: 1px solid #444;
      }
      .form-control {
          background-color: #333;
          color: #ffffff;
          border-color: #555;
      }
      .panel-default {
          background-color: #333;
          border-color: #444;
      }
      .panel-default > .panel-heading {
          background-color: #444;
          border-color: #555;
          color: #ffffff;
      }
      .panel-body {
          color: #ccc;
      }
      .panel-heading h3 {
          margin: 0;
      }
    </style>


    {% bootstrap_javascript %}
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'blogs:index' %}">
            Blog
          </a>
        </div>

        <div id="navbar" class="navbar-collapse">
          <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
            <li><a href="{% url 'blogs:new_blogpost' %}">Add New Post</a></li>
            {% endif %}          
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}</a></li>
              <li><a href="{% url 'users:logout' %}">Log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">Register</a></li>
              <li><a href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div>
  </body>

20_styling_and_deploying_an_app/blog_app/blogs/templates/blogs/edit_blogpost.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>{{ blogpost.title }}</h2>
{% endblock header %}

{% block content %}

  <h3>Edit blogpost:</h3>

    <form action="{% url 'blogs:edit_blogpost' blogpost.id %}" method='post'
      class = "form">
      
        {% csrf_token %}
        {% bootstrap_form form %}

      {% buttons %}  
        <button name="submit" class="btn btn-default">Save changes</button>
      {% endbuttons %}

    </form>

{% endblock content %}

20_styling_and_deploying_an_app/blog_app/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block header %}
  <div class="jumbotron">
    <h1>Post your own blog!</h1>
  </div>
{% endblock header %}

{% block content %}
  {% for blogpost in blogposts %}
    <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            {{ blogpost.title }}
            <span class="pull-right">
                <small style="color: #999; margin-right: 10px;">
                    {{ blogpost.date_added|date:"M d, Y" }}
                </small>
                {% if user.is_authenticated and blogpost.owner == user %}
                  <a href="{% url 'blogs:edit_blogpost' blogpost.id %}"
                    class="btn btn-xs btn-default">
                    Edit blogpost
                  </a>
                {% endif %}
            </span>
          </h3>
        </div>
        <div class="panel-body">
            {{ blogpost.text }}
        </div>
    </div>

  {% empty %}
    No blogposts have been added yet.
  {% endfor %}

  <hr>


  {% if user.is_authenticated %}
    <a href="{% url 'blogs:new_blogpost' %}" class="btn btn-default">Add New Post</a>
  {% else %}
    <a href="{% url 'users:register' %}">Register an account</a> to create
      your own blog post.
  {% endif %}

{% endblock content %}

20_styling_and_deploying_an_app/blog_app/blogs/templates/blogs/new_blogpost.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new blogpost</h2>
{% endblock header %}


{% block content %}
    <form action="{% url 'blogs:new_blogpost' %}" method='post'
      class="form">

        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
          <button name="submit" class="btn btn-default">Add Post</button>
        {% endbuttons %}

    </form>

{% endblock content %}

20_styling_and_deploying_an_app/blog_app/users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log into your account.</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-default">log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
  </form>

{% endblock content %}

20_styling_and_deploying_an_app/blog_app/users/templates/users/register.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Register an account.</h2>
{% endblock header %}

{% block content %}

    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
        <button name="submit" class="btn btn-default">register</button>
        {% endbuttons %}
        
        <input type="hidden" name="next" value="{% url 'blogs:index' %}" />
    </form>

{% endblock content %}