18_getting_started_with_django/learning_logs/urls.py
"""Defines URL patterns for learning_logs."""

from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Home page
    path("", views.index, name= "index"),

    # Show all topics
    path("topics/", views.topics, name="topics"),

    # Detail page for a single topic
    path("topics/<int:topic_id>/", views.topic, name="topic"),
]

18_getting_started_with_django/learning_logs/views.py
from django.shortcuts import render
from .models import Topic

# Create your views here.
def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')  # type: ignore
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

18_getting_started_with_django/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block content %}

  <p>Topic: {{ topic }}</p>

  <p>Entries:</p>
    <ul>
        {% for entry in entries %}
          <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
          </li>
        {% empty %}
          <li>
            <p>There are no entries for this topic yet.</p>
          </li>
        {% endfor %}
    </ul>
{% endblock content %}

18_getting_started_with_django/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <h2>Topics</h2>
  
  <ul>
    {% for topic in topics %}
      <li>
        <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      </li>
    {% empty %}
      <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}